(prevTable as table,UserID) as text=>
let 
    FilterTableByUser = Table.SelectRows(prevTable,each [Child]=UserID),
    GetTheParent =  FilterTableByUser[Parent]{0}
in 
    if GetTheParent = null then Text.From(UserID)
    else 
          Text.From(@#"Invoked Function"#f(prevTable,GetTheParent)) & "|" & Text.From(UserID) 
