(Search as text) as table=>
let
    Source = Json.Document(Web.Contents("https://api.github.com/repos/AngeloParana/Public/contents/mFunctions")),
    FlatTable = Table.FromList(Source, Splitter.SplitByNothing(), {"Functions"}, null, ExtraValues.Error),
    ExpandFunctions = Table.ExpandRecordColumn(FlatTable, "Functions", {"name", "download_url"}),
    SearchFunction = Table.SelectRows(ExpandFunctions, each Text.Contains([name],Search,Comparer.OrdinalIgnoreCase)),
    GetFunction = Table.AddColumn(
                                SearchFunction, "File", each 
                                        Text.FromBinary(Web.Contents([download_url]))
                                    )
in
    GetFunction
